/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_4_4

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun <T> List<T>.head(): T =
        if (this.isEmpty())
            throw IllegalArgumentException("head called on empty list")
        else
            this[0]

fun <T> List<T>.tail(): List<T> =
        if (this.isEmpty())
            throw IllegalArgumentException("tail called on empty list")
        else
            this.drop(1)



fun <T> makeString(list: List<T>, delim: String): String {
    tailrec fun makeString_(list: List<T>, acc: String): String =
		when {
			list.isEmpty() -> acc
			acc.isEmpty() -> makeString_(list.tail(), "${list.head()}")
			else -> makeString_(list.tail(), "$acc$delim${list.head()}")
		}
	return makeString_(list, "")
}


fun main() {
    println(App().greeting)
	println(makeString(listOf("a", "b", "c","d"), " delim "))
}
